ARG GOLANG_VERSION=1.23.2
ARG ALPINE_VERSION=3.20

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION} AS main-linux-arm64
RUN apk add --no-cache ucl

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION} AS main-linux-amd64
RUN apk add --no-cache ucl

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION} AS main-linux-armv7
RUN apk add --no-cache ucl

FROM main-${TARGETOS}-${TARGETARCH}${TARGETVARIANT}
RUN go install github.com/a-h/templ/cmd/templ@latest
