ARG GOLANG_VERSION=1.23.3
ARG ALPINE_VERSION=3.20

# https://stackoverflow.com/questions/75209245/golang-cross-compiling-with-cgo-inside-docker-image/76440207#76440207
# https://github.com/tonistiigi/xx/blob/master/README.md#go--cgo

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}
RUN apk add --no-cache upx
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install golang.org/x/vuln/cmd/govulncheck@latest
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.62.0
