ARG GOLANG_VERSION=""
ARG ALPINE_VERSION=""
ARG GOLANGCI_LINT_VERSION=""
# https://stackoverflow.com/questions/75209245/golang-cross-compiling-with-cgo-inside-docker-image/76440207#76440207
# https://github.com/tonistiigi/xx/blob/master/README.md#go--cgo

FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}
ARG GOLANGCI_LINT_VERSION
RUN apk add --no-cache upx bash curl
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v${GOLANGCI_LINT_VERSION}
RUN go install github.com/a-h/templ/cmd/templ@latest          && \
    go install golang.org/x/vuln/cmd/govulncheck@latest       && \
    go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest  && \
    rm -rf /go/pkg/*
